[package]
name = "threadx-sys"
version = "0.1.0"
authors = ["Sojan James <Sojan.James@gmail.com>"]
edition = "2021"
description = "Rust bindings for ThreadX"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
